package com.donatoordep.enums;

public enum CurrencyCode {
    USD, AUD, BGN, CAD, EUR, SDG, IQD, CUP, GMD, TWD, RSD, DOP, KMF, MYR, FKP,
    XOF, GEL, UYU, MAD, CVE, TOP, AZN, OMR, PGK, KES, SEK, BTN, UAH, GNF, ERN,
    GBP, EGP, CNY, CHF, FJD, MXN, SCR, TVD, CDF, BBD, GTQ, CLP, HNL, UGX, ZAR,
    TND, STN, SLE, BSD, SLL, MZN, ARS, QAR, IRR, THB, UZS, XPF, MRU, BDT, LYD,
    BMD, KWD, PHP, RUB, PYG, ISK, JMD, COP, MKD, DZD, PAB, GGP, SGD, ETB, JEP,
    KGS, SOS, VUV, LAK, BND, XAF, LRD, HRK, ALL, DJF, VES, ZMW, TZS, VND, ILS,
    GHS, GYD, BOB, KHR, MDL, IDR, KYD, AMD, BWP, SHP, TRY, LBP, TJS, JOD, AED,
    HKD, RWF, FOK, LSL, DKK, KID, MMK, MUR, NOK, SYP, IMP, ZWL, GIP, RON, LKR,
    NGN, CRC, CZK, PKR, XCD, ANG, HTG, BHD, KZT, SRD, SZL, SAR, TTD, YER, MVR,
    AFN, INR, AWG, KRW, NPR, JPY, MNT, AOA, PLN, SBD, BYN, HUF, BIF, MWK, MGA,
    XDR, BZD, BAM, MOP, NAD, SSP, NIO, PEN, NZD, WST, TMT, BRL
}